//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
PRINT Run all te_TestServer Suite Tests

LOAD_SUITE te_TestServerSuite -ShareData

RUN_TEST_STEP 100 te_TestServerSuite ValidStep
RUN_TEST_STEP 100 te_TestServerSuite PanicStep
RUN_TEST_STEP 100 te_TestServerSuite ErrorStep

