/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies). 
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
package com.nokia.s60tools.testdrop.resources;

/**
 * Contains ids for context sensitive help
 * 
 */
public class TestDropHelpContextIDs {
	private static final String TEST_DROP_HELP_PROJECT_PLUGIN_ID = "com.nokia.s60tools.testdrop.help";

	public static final String TESTDROP_SEND_DIALOG_CHECKBOX = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_SEND_DIALOG_CHECKBOX";
	public static final String TESTDROP_SEND_DIALOG_TARGET_DEVICE_LIST = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_SEND_DIALOG_TARGET_DEVICE_LIST";
	public static final String TESTDROP_SEND_DIALOG_SEND_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_SEND_DIALOG_SEND_BUTTON";
	public static final String TESTDROP_SEND_DIALOG_CANCEL_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_SEND_DIALOG_CANCEL_BUTTON";

	public static final String TESTDROP_IMAGE_SELECTION_DIALOG_LIST = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_IMAGE_SELECTION_DIALOG_LIST";
	public static final String TESTDROP_IMAGE_SELECTION_DIALOG_REMOVE_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_IMAGE_SELECTION_DIALOG_REMOVE_BUTTON";
	public static final String TESTDROP_IMAGE_SELECTION_DIALOG_BROWSE_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_IMAGE_SELECTION_DIALOG_BROWSE_BUTTON";
	public static final String TESTDROP_IMAGE_SELECTION_DIALOG_SEND_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_IMAGE_SELECTION_DIALOG_SEND_BUTTON";
	public static final String TESTDROP_IMAGE_SELECTION_DIALOG_CANCEL_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_IMAGE_SELECTION_DIALOG_CANCEL_BUTTON";

	public static final String TESTDROP_PREFERENCES_HOST = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_HOST";
	public static final String TESTDROP_PREFERENCES_PORT = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_PORT";
	public static final String TESTDROP_PREFERENCES_USERNAME = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_USERNAME";
	public static final String TESTDROP_PREFERENCES_PASSWORD = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_PASSWORD";
	public static final String TESTDROP_PREFERENCES_CONFIRM_PASSWORD = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_CONFIRM_PASSWORD";
	public static final String TESTDROP_PREFERENCES_TEST_CONNECTION = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TEST_CONNECTION";
	public static final String TESTDROP_PREFERENCES_SHOW_DIALOG_ALWAYS = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_SHOW_DIALOG_ALWAYS";
	public static final String TESTDROP_PREFERENCES_TARGET_DEVICE_LIST_CACHE = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TARGET_DEVICE_LIST_CACHE";
	public static final String TESTDROP_PREFERENCES_DEFAULT = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_DEFAULT";
	public static final String TESTDROP_PREFERENCES_DEFAULT_TARGET_DEVICE_LIST = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_DEFAULT_TARGET_DEVICE_LIST";
	public static final String TESTDROP_PREFERENCES_DEFAULT_SET_IMAGES = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_DEFAULT_SET_IMAGES";
	public static final String TESTDROP_PREFERENCES_DEFAULT_TARGET_DEVICE_IMAGE_SELECTION_DIALOG_SAVE_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_DEFAULT_TARGET_DEVICE_IMAGE_SELECTION_DIALOG_SAVE_BUTTON";
	public static final String TESTDROP_PREFERENCES_DEFAULT_TARGET_DEVICE_IMAGE_SELECTION_DIALOG_CANCEL_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_DEFAULT_TARGET_DEVICE_IMAGE_SELECTION_DIALOG_CANCEL_BUTTON";
	public static final String TESTDROP_PREFERENCES_TEST_DROP_ENABLE_IMPORT = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TEST_DROP_ENABLE_IMPORT";
	public static final String TESTDROP_PREFERENCES_TEST_DROP_PATH_BUTTON = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TEST_DROP_PATH_BUTTON";
	public static final String TESTDROP_PREFERENCES_TEST_DROP_PATH = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TEST_DROP_PATH";
	public static final String TESTDROP_PREFERENCES_TEST_RESULT_VIEW = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TEST_RESULT_VIEW";
	public static final String TESTDROP_PREFERENCES_TEST_RESULT_PATH = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TEST_RESULT_PATH";
	public static final String TESTDROP_PREFERENCES_TEST_RESULT_PATH_BROWSE = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_TEST_RESULT_PATH_BROWSE";
	public static final String TESTDROP_PREFERENCES_APPLY = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_APPLY";
	public static final String TESTDROP_PREFERENCES_OK = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_PREFERENCES_OK";

	public static final String TESTDROP_RESULTS_VIEW = TEST_DROP_HELP_PROJECT_PLUGIN_ID
			+ ".TESTDROP_RESULTS_VIEW";

}
