//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
PRINT Run all Sample Tests 
//
LOAD_SUITE SampleServer
//
#
RUN_UTILS MkDir c:\SampleTest\
RUN_UTILS MakeReadWrite c:\SampleTest\SampleTest1.Script
RUN_UTILS MakeReadWrite c:\SampleTest\SampleTest.ini

RUN_TEST_STEP 100 SampleServer SampleStep2  c:\sampletest\sampleTest.ini SectionOne
