/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/


//header file for the interface between the C++ STAT component and Java.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_symbian_jstat_JStat */

#ifndef _Included_com_symbian_jstat_JStat
#define _Included_com_symbian_jstat_JStat
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_symbian_jstat_JStat
 * Method:    connect
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_symbian_jstat_JStatRunCommand_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_symbian_jstat_JStat
 * Method:    disconnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_symbian_jstat_JStatRunCommand_disconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_symbian_jstat_JStat
 * Method:    doCommand
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_symbian_jstat_JStatRunCommand_doCommand
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_symbian_jstat_JStat
 * Method:    getError
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_symbian_jstat_JStatRunCommand_getError
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_symbian_jstat_JStat
 * Method:    getReceivedData
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_symbian_jstat_JStatRunCommand_getReceivedData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_symbian_jstat_JStat
 * Method:    getStatVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_symbian_jstat_JStat_getStatVersion
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
