/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies). 
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/


package com.nokia.s60tools.stif.scripteditor.utils;

import org.eclipse.jface.viewers.ArrayContentProvider;
import org.eclipse.jface.viewers.ITreeContentProvider;

/**
 * Class needed for outline view to work. The items in outline view currerntly do
 * not have parent/children nodes. That's why the autogenerated implementation is used 
 */
public class OutlinePageContentProvider extends ArrayContentProvider 
	implements ITreeContentProvider {
	
	public Object getParent(Object arg0) {
		return null;
	}
	
	public Object[] getChildren(Object arg0) {
		return null;
	}
	
	public boolean hasChildren(Object arg0) {
		return false;
	}
}
