/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Utils */

#ifndef _Included_Utils
#define _Included_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Utils
 * Method:    getPidList
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_symbian_nativeprocesshandler_ProcessHandler_getPidList
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Utils
 * Method:    kill
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_symbian_nativeprocesshandler_ProcessHandler_kill
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
