<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="script"
    nsURI="http://www.symbian.com/tef" nsPrefix="tef.script">
  <eClassifiers xsi:type="ecore:EClass" name="TefModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tef" lowerBound="1" upperBound="-1"
        eType="#//Tef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tef" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true" interface="true"
      eSuperTypes="#//Tef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tef" upperBound="-1" eType="#//Tef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" abstract="true" interface="true"
      eSuperTypes="#//Tef"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase" eSuperTypes="comment.ecore#//AttachedComment #//Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prefix" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//SectionPesistance #//Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStep" eSuperTypes="comment.ecore#//AttachedComment #//SectionPesistance #//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="server" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="pattern" value="\S+"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PanicString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="pattern" value="\S+"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PanicCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="pattern" value="\S+"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Heap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OOM" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Print" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="print" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadSuite" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="server" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sharedData" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadServer" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="server" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sharedData" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunUtils" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilityCommand" lowerBound="1"
        eType="#//UtilityCommand" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="param" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UtilityCommand">
    <eLiterals name="MakeReadWrite"/>
    <eLiterals name="DeleteFile" value="1"/>
    <eLiterals name="DeleteDirectory" value="2"/>
    <eLiterals name="CopyFile" value="3"/>
    <eLiterals name="MkDir" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunProgram" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Timeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WS" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunScript" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptPersistance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="#//Leaf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consecutive" eSuperTypes="#//Leaf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Concurrent" eSuperTypes="#//Leaf"/>
  <eClassifiers xsi:type="ecore:EClass" name="SharedData" eSuperTypes="#//SectionPesistance #//Leaf"/>
  <eClassifiers xsi:type="ecore:EClass" name="SectionPesistance" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" lowerBound="1"
        eType="ecore:EClass ini.ecore#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iniPersistance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionPersistance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TefComment" eSuperTypes="comment.ecore#//Comment #//Leaf"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestBlock" eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Heap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="1048576" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="server" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iniFile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PanicCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PanicString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateObject" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RestoreObject" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AsyncError" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" eType="ecore:EClass ini.ecore#//Section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" lowerBound="1"
        eType="ecore:EClass ini.ecore#//Section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outstanding" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pollInterval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsyncDelay" eSuperTypes="#//Leaf">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharedActiveScheduler" eSuperTypes="#//Leaf"/>
  <eClassifiers xsi:type="ecore:EClass" name="StoreActiveScheduler" eSuperTypes="#//Leaf"/>
</ecore:EPackage>
